#!/usr/bin/env python3
"""A Python module generates returns 10 rand num using async comprehension."""
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random numbers.
    Uses an asynchronous comprehension to gather random nu
    generated by the async_generator.
    Returns:
        A list containing 10 random float values.
    """
    random_numbers = [c async for c in async_generator()]
    return random_numbers
